### ISSUE TITLE
Post import for task holder

### ISSUE THREAD

**Issue by paulondc** [kombiHQ/kombi#39]
Add a way to defined a post import for a task holder configuration when a specific task is completed. For instance:

```yaml
tasks:
- run: ingestion
  metadata:
    match.types:
    - exr
   # ...
- run: deflate
  metadata:
    match.types:
    - zip
    - tar
    - targz
  target: "(dirname {fullPath})/{name}"
  tasks:
  - run: glob
    options:
      types:
      - exr
      - zip
      - tar
      - tarfz
    postImport: "{contextConfig}"
```

The idea is to be able provide recursion through this syntax. For instance, deflating a file then re-running the configuration again, and so on.
