### ISSUE TITLE
unpack task

### ISSUE THREAD

**Issue by paulondc** [kombiHQ/kombi#40]
Add a task for decompressing/unpacking zip, tar and tar.gz

```yaml
- run: unpack
  metadata:
    match.types:
    - zip
    - tar
    - targz
```
