### ISSUE TITLE
Pack Task

### ISSUE THREAD

**Issue by paulondc** [kombiHQ/kombi#41]
Add a task for compressing/packing zip, tar and tar.gz

```yaml
- run: pack
  option:
    type: "zip"
  target: "{name}.zip"
```
